### ISSUE TITLE
ffmpeg doesn't build because of dependency to dcadec >= 0.1.0

### ISSUE THREAD

**Issue by gdachs** [plexinc/OpenELEC.tv#27]
IMHO it is a very bad idea to have PKG_VERSION="master" in packages/multimedia/ffmpeg/package.mk.
That makes ffmpeg a running target. Because of this ffmpeg currently doesn't build anymore. The dcadec version is not matching.
After this is fixed, use a release that is known for building please.

Gerald

**Comment by wm4** [comment]
It actually points at my own tree, which I update as needed: https://github.com/wm4/FFmpeg

(And this didn't bump to libdcadec 0.2.0 yet.)

But it's true that we should update libdcadec.

**Comment by gdachs** [comment]
So I suppose if you would do a "make clean" you should get a problem to rebuild it again. 
I am working on a Patch for HDMI-CEC one touch play on the RPi2. I had to disable usage of dcadec in ffmpeg to get ffmpeg build working.

**Comment by gdachs** [comment]
In the meantime I have seen that it is not the version generally that is the problem, it is the dcadec.pc file that contains the Version 0.0.0, but changing it, lets it stop later because of a missing define, so I gave up.

**Comment by gdachs** [comment]
shit, can't build a working release file with the current state in github, even without my patch. The result just crashes periodically with SIGSEGV and shows nothing in the logs.

Please tell me if it works again.

**Comment by gdachs** [comment]
Trying a fresh build on another machine worked, sorry for the noise

**Comment by wm4** [comment]
It might be possible that ccache is the cause for your problems. It dumps state into `~/.ccache/` and/or `~/.ccache-openelec/`. Deleting it once helped me. (Normally the cache shouldn't cause problems, but sometimes it does - found that out in the hard way.)

**Comment by gdachs** [comment]
You might be right, but the build result doesn't work. The plex media player crashes with and without my patch shortly after start :(
