### ISSUE TITLE
current build crashes with segfault in cycles

### ISSUE THREAD

**Issue by gdachs** [plexinc/OpenELEC.tv#28]
A fresh build for a Raspberry Pi 2 crashes on start of plex.service with a segfault.
The attached files don't show the reason. How can I dig deeper into the issue?
[journalclt.txt](https://github.com/plexinc/OpenELEC.tv/files/93453/journalclt.txt)
[plexmediaplayer.log.txt](https://github.com/plexinc/OpenELEC.tv/files/93456/plexmediaplayer.log.txt)

**Comment by wm4** [comment]
It appears to crash around the display manager code. This is suspicious, maybe someone (me) actually broke something.

**Comment by gdachs** [comment]
Ping me if I can try it again, please. I am eager for trying a patch for the plex media player I made.
